spring:
  application:
    name: basic-arch-serial-flyway
flyway:
  enabled: true
  defaultParams: serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull
  jdbc:
    defaultParam: serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://mysql.local.com
    driverClassName: com.mysql.cj.jdbc.Driver
    master0:
      url: ${flyway.jdbc.url}:3307/arch_common?${flyway.jdbc.defaultParam}
      wAccount: admin
      wPassword: 1RNbTI@m$zIE114s
  ds:
    - driver: ${flyway.jdbc.driverClassName}
      url: ${flyway.jdbc.master0.url}
      user: ${flyway.jdbc.master0.wAccount}
      password: ${flyway.jdbc.master0.wPassword}
      clean-disabled: false
      locations: classpath:db/migration/master0
      table: flyway_schema_history
      baseline-on-migrate: true
      baseline-version: 1
      encoding: UTF-8
      out-of-order: false
      schemas: arch_common
      validate-on-migrate: true
      default-schema: arch_common
