/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
SET NAMES utf8mb4;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `serial_alloc`;

CREATE TABLE `serial_alloc`
(
    `biz_tag`     varchar(128) NOT NULL DEFAULT '' COMMENT '业务Key',
    `max_id`      bigint(20) NOT NULL DEFAULT '1' COMMENT '最大已使用ID',
    `step`        int(11) NOT NULL COMMENT '步长',
    `random_len`  int(11) NOT NULL DEFAULT '0' COMMENT '尾部随机数位数',
    `description` varchar(256) NOT NULL DEFAULT '' COMMENT '描述',
    `status`      int(11) NOT NULL DEFAULT '0' COMMENT '状态(0 正常 1 禁用 2 删除)',
    `create_time` datetime     NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '创建时间',
    `update_time` timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`biz_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='序列号';
